/**
 * Provides animal representations for anonymous users.
 * Defines animal icons and fetches at random for each new account.
 */

export const animals: string[] = [
    "Alligator",
    "Ant",
    "Bat",
    "Bear",
    "Bee",
    "Bird",
    "Butterfly",
    "Camel",
    "Cat",
    "Centipede",
    "Chinchilla",
    "Chicken",
    "Cheetah",
    "Clam",
    "Cow",
    "Crab",
    "Crocodile",
    "Deer",
    "Dog",
    "Dolphin",
    "Donkey",
    "Dragonfly",
    "Duck",
    "Eagle",
    "Elephant",
    "Fox",
    "Frog",
    "Giraffe",
    "Goat",
    "Goose",
    "Gorilla",
    "Hamster",
    "Hawk",
    "Hippo",
    "Horse",
    "Hyena",
    "Jellyfish",
    "Kangaroo",
    "Ladybug",
    "Leopard",
    "Lion",
    "Lizard",
    "Lobster",
    "Llama",
    "Moose",
    "Monkey",
    "Mouse",
    "Octopus",
    "Ostrich",
    "Owl",
    "Oyster",
    "Parrot",
    "Panda",
    "Penguin",
    "Peacock",
    "Pig",
    "Rabbit",
    "Racoon",
    "Rhino",
    "Rooster",
    "Seal",
    "Shark",
    "Sheep",
    "Shrimp",
    "Skunk",
    "Snake",
    "Snail",
    "Spider",
    "Starfish",
    "Swan",
    "Tiger",
    "Turtle",
    "Turkey",
    "Walrus",
    "Whale",
    "Wolf",
    "Worm",
    "Zebra",
];

export const animalMap: Record<string, string> = {
    "Alligator": "🐊",
    "Ant": "🐜",
    "Bat": "🦇",
    "Bear": "🐻",
    "Bee": "🐝",
    "Bird": "🐦",
    "Butterfly": "🦋",
    "Camel": "🐪",
    "Cat": "🐱",
    "Centipede": "🐛",
    "Chicken": "🐔",
    "Cheetah": "🐆",
    "Chinchilla": "🦙",
    "Clam": "🐚",
    "Cow": "🐮",
    "Crab": "🦀",
    "Crocodile": "🐊",
    "Deer": "🦌",
    "Dog": "🐶",
    "Dolphin": "🐬",
    "Donkey": "🐴",
    "Dragonfly": "🐉",
    "Duck": "🦆",
    "Eagle": "🦅",
    "Elephant": "🐘",
    "Fox": "🦊",
    "Frog": "🐸",
    "Giraffe": "🦒",
    "Goat": "🐐",
    "Goose": "🦢",
    "Gorilla": "🦍",
    "Hamster": "🐹",
    "Hawk": "🦅",
    "Hippo": "🦛",
    "Horse": "🐴",
    "Hyena": "🐺",
    "Jellyfish": "🐙",
    "Kangaroo": "🦘",
    "Ladybug": "🐞",
    "Leopard": "🐆",
    "Lion": "🦁",
    "Lizard": "🦎",
    "Lobster": "🦞",
    "Llama": "🦙",
    "Moose": "🦌",
    "Monkey": "🐵",
    "Mouse": "🐭",
    "Octopus": "🐙",
    "Ostrich": "🐦",
    "Owl": "🦉",
    "Oyster": "🦪",
    "Parrot": "🦜",
    "Panda": "🐼",
    "Penguin": "🐧",
    "Peacock": "🦚",
    "Pig": "🐷",
    "Rabbit": "🐰",
    "Racoon": "🦝",
    "Rhino": "🦏",
    "Rooster": "🐓",
    "Seal": "🦭",
    "Shark": "🦈",
    "Sheep": "🐑",
    "Shrimp": "🦐",
    "Skunk": "🦨",
    "Snake": "🐍",
    "Snail": "🐌",
    "Spider": "🕷️",
    "Starfish": "🌟",
    "Swan": "🦢",
    "Tiger": "🐅",
    "Turtle": "🐢",
    "Turkey": "🦃",
    "Walrus": "🦭",
    "Whale": "🐋",
    "Wolf": "🐺",
    "Worm": "🪱",
    "Zebra": "🦓",
};

/**
 * Randomly selects icon
 * @returns random animal
 */
export function getRandomAnimal(): string {
    const randomIndex = Math.floor(Math.random() * animals.length);
    return animals[randomIndex];
}

/**
 * Returns icon for animal
 * @param animal 
 * @returns corresponding icon
 */
export function getAnimalEmoji(animal: string): string {
    return animalMap[animal] || "";
}
